Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end
  config.vm.network "forwarded_port", guest: 8085, host: 8080
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/configure-ci-server.yml"
	ansible.inventory_path = "ansible/hosts"
	ansible.become = true
  end
end